### ISSUE TITLE
Set up : Netlify

### ISSUE THREAD

**Issue by Iseluin** [ReCoded-Org/capstone-IQLBPS-Dilmun#7]
## Summary

Deploy the project on Netlify, also configure Netlify so continious deployment runs every time there is a PR.

Dev branch must be deployed.

### Screenshots

N/A

### Basic example

N/A

### Motivation

Will be used so we are able to see a live version of the project and the changes will be seen live every time a PR is made.

**Comment by karzan7899** [comment]
done!

**Comment by karzan7899** [comment]
This is the link: https://remarkablesunburst.netlify.app/
